### ISSUE TITLE
Refresh Add_on

### ISSUE THREAD

**Issue by Atreyus86** [BryanCrotaz/blender-artnet#9] opened 2020-08-02 17:10 UTC
When i close the project and after that i re-open the same project, i have to uncheck and recheck the flag on the ArtNet addon and only after that it starts to work again

**Comment by BryanCrotaz** [comment] 2020-08-03 01:09
I can't reproduce this with 1.4 - please test again

**Comment by BryanCrotaz** [comment] 2020-08-03 01:10
there is a bug fix in 1.4 where the artnet socket wasn't closed properly if the plugin was unloaded.

**Comment by Atreyus86** [comment] 2020-08-03 15:49
when i close and re-open one project with only one fixture (maybe even 2 - 4 - 6) the refresh work perfectly, but when i open other project with 32 fixture (i don't know why) the refresh don't  work.

**Comment by BryanCrotaz** [comment] 2020-08-03 15:51
Can you pm me your blender file?

**Comment by Atreyus86** [comment] 2020-08-03 17:53
yes off course, how can i send you in PM mode?

**Comment by BryanCrotaz** [comment] 2020-08-03 22:33
Email is on my profile

**Comment by BryanCrotaz** [comment] 2020-08-16 05:13
Fixed in v1.5

**Closed as completed by BryanCrotaz** 2020-08-16 05:13 UTC
